name: Publish Dev Website
on:
  push:
    branches: [ main ]

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn install
    - run: yarn build
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        local-dir: build
        ftp-server: ftp://72.167.125.79/public_html
        ftp-username: i3z6zteowp5y
        ftp-password: ${{ secrets.WEBSITE_FTP_PASSWORD }}
        known-hosts: ${{ secrets.WEBSITE_KNOWN_HOSTS }}
        args: --all
